### ISSUE TITLE
suggestion: add msvcp120.dll etc to project

### ISSUE THREAD

**Issue by torekp** [oysstu/LabVIEW-libsvm#6]
When using LabVIEW to build an executable or installer, it is tricky to include the right DLLs.  LabVIEW does not automatically include DLLs used within DLLs.  For 32 bit libsvm on Windows, one needs to include msvcp120.dll and msvcr120.dll from C:\Windows\System32 in the project, and also LabVIEW-libsvm.dll.  In the Destinations tab of a Build specification, add the folder that will contain the .exe as a new destination.  On the Source File Settings tab, make sure all these DLLs will go to that folder.

oysstu, you have already included a nice LabVIEW project file. You could add the above mentioned DLLs into the project's file list, and add the above info to the Readme.

**Comment by oysstu** [comment]
This is precisely why Visual Studio 2013 Visual C++ Redistributable is listed as a dependency, as it installs the required DLLs onto the target system. I could add the DLLs to the project, but will that not cause the DLLs to be distributed with the exe? Is that desirable given that redistributable installs are the regular way of handling these dependencies?

I suppose since LabVIEW programs are typically not installed, it makes sense to distribute it with all dependencies. I'll update the project file and clarify the readme.

**Comment by torekp** [comment]
Thanks oysstu.

I did have VS 2013 Redistributable on the target computer.  But, Labview Run Time Engine couldn't figure out how to handle the DLLs, even though I had LabVIEW-libsvm.dll in the EXE's folder.  It claimed not to have access to the resource LabVIEW-libsvm.dll.  That is, until I did as described above.  Then, no problem.

**Comment by oysstu** [comment]
I'm in the progress of deploying a new version. I've built an exe of one of the examples in the library and haven't had the problem you describe. LabVIEWs Run Time Engine is not the one loading the external library, that is performed by the C++ runtime. As long as the required DLLs are in the search path, it should be found and automatically loaded (e.g in System32).

**Comment by oysstu** [comment]
I believe I have addressed this in the latest release/project file. Note that the Visual Studio 2017 runtime is now required. Let me know if the problem persists
